all:
  children:
    land:  # Devices on Landstraße location
      hosts:
        opnsense-land: 
          ansible_host: 10.0.0.1
        nas:
          ansible_host: 10.0.0.20
        unifi:
          ansible_host: 10.0.0.21
        docker-core:
          ansible_host: 10.0.0.22
        sync:
          ansible_host: 10.0.0.26
        paperless:
          ansible_host: 10.0.0.30
          compose_file: /home/paperless/paperless-ngx  # Specific variable for paperless
        immich:
          ansible_host: 10.0.0.47
        argon:
          ansible_host: 10.0.0.10
        #pbs:
        #  ansible_host: 10.0.0.14
        rezepte:
          ansible_host: 10.0.0.42
        joplin:
          ansible_host: 10.0.0.49
        homarr:
          ansible_host: 10.0.0.25
        jdown:
          ansible_host: 10.0.0.44
        ansible:
          ansible_host: 10.0.0.50
        vscode:
          ansible_host: 10.0.0.51
        speedtest:
          ansible_host: 10.0.0.48
        send:
          ansible_host: 10.0.0.53
        semaphore:
          ansible_host: 10.0.0.55
        netboot:
          ansible_host: 10.0.0.23
        media:
          ansible_host: 10.11.0.3
        filesrv:
          ansible_host: 10.0.0.254 
      children:
        fileserver:    # Svers that share files over SMB
          hosts:
            nas:
            media:            
            filesrv:
        docker:    # Docker hosts
          hosts:
            docker-core:
            paperless:
            immich:
            rezepte:          
            joplin:           
            homarr:           
            jdown:            
            speedtest:        
            send:             
            netboot:          
          vars: 
            compose_file: /docker  # General variable for docker hosts
        bare_metal:
          hosts:
            argon:
            #pbs:
            opnsense-land:
        debian:
          hosts:
            nas:
            docker-core:
            immich:
            rezepte:          
            joplin:           
            homarr:           
            jdown:            
            ansible:          
            vscode:           
            speedtest:        
            send:             
            semaphore:        
            netboot:          
            media:            
            filesrv:          
        ubuntu:
          hosts:
            unifi:
        opnsense:  # Firewall
          hosts:
            opnsense-land:
    exposed:  # Devices accessible from the internet
      hosts:
        docker-core:
        immich:
        joplin:           
        jdown:
        opnsense-land:
    see:  # Devices on Seestraße location
      hosts:
        opnsense-see:
          ansible_host: 10.1.0.1
        futro-seestr: 
          ansible_host: 10.1.0.5
        unifi-see: 
          ansible_host: 10.1.0.15
        omv: 
          ansible_host: 10.1.0.10
          compose_file: /srv/dev-disk-by-label-HGST8TB/shares/docker/ 
      children:
        bare_metal:
          hosts:
            futro-seestr: 
            omv:
            opnsense-see: 
        ubuntu:
          hosts:
            unifi-see: 
        debian:
          hosts:
            omv: 
        fileserver:    # Svers that share files over SMB
          hosts:
            omv: 
        docker:    # Docker hosts
          hosts:
            omv:
        opnsense:  # Firewall
          hosts:
            opnsense-see:
        exposed:  # Devices accessible from the internet
          hosts:
            opnsense-see: