---
# This playbook updates and upgrades an OPNsense firewall using the API.
- name: Update and upgrade OPNsense firewall
  hosts: localhost  # Target group of OPNsense firewalls
  gather_facts: no
  collections:
    - ansibleguy.opnsense
  module_defaults:
    ansibleguy.opnsense.system:
      firewall: '10.1.0.1'
      api_credential_file: '/home/manu/.secret/opnsense_landstr.key'

  tasks:
    - name: Pull updates
      ansibleguy.opnsense.system:
#        firewall: '10.1.0.1'
#        api_credential_file: '/home/manu/.secret/opnsense_landstr.key'
        action: 'update'

    - name: Start upgrade # will wait until finished (WARNING: ONLY USE IN TEST-ENVIRONMENTS)
      ansibleguy.opnsense.system:
        action: 'upgrade'
        timeout: 180  # depends on your download speed and firmware-version
        force_upgrade: true